fix pdfviewer on public pages
nextcloud/files_pdfviewer pull request #655
Opened 2022-09-07 08:38 UTC by szaimen

Close https://github.com/nextcloud/server/issues/33871

Signed-off-by: szaimen <szaimen@e.mail.de>

2022-09-07 09:00 UTC, szaimen commented
/compile amend /

2022-09-07 13:02 UTC, danxuliu requested changes
The bottom of the PDF viewer overflows the window, because [the minimum height of the content is set to 100%](https://github.com/nextcloud/files_pdfviewer/blob/e01afb8ea98a1b6a342c93e5c6edc4b8262adcea/src/public.js#L74). However, with the new style it seems that the minimum height must take into account the height of the header, so it should be `calc(100% - 50px)` (or something similar) instead.

Besides that please note that this may need to be adjusted again once https://github.com/nextcloud/server/issues/33803 is fixed.

2022-09-08 09:57 UTC, szaimen commented
> The bottom of the PDF viewer overflows the window, because [the minimum height of the content is set to 100%](https://github.com/nextcloud/files_pdfviewer/blob/e01afb8ea98a1b6a342c93e5c6edc4b8262adcea/src/public.js#L74). However, with the new style it seems that the minimum height must take into account the height of the header, so it should be `calc(100% - 50px)` (or something similar) instead.

done

2022-09-08 12:52 UTC, skjnldsv approved these changes

2022-09-08 12:53 UTC, merged